server:
  port: 8763

spring:  application:    name: gateway
  cloud:    gateway:      routes:      - id: book
        uri: lb://book        predicates:        - Path=/book/**
        filters:        - RewritePath=/book(?<segment>/?.*), $\{segment}

eureka:
  instance:
    prefer-ip-address: true  client:    service-url:      defaultZone: ${EUREKA_URL:http://localhost:8762/eureka}
    register-with-eureka: true
    fetch-registry: true

logging:  file:    name: /app/gateway/app.log